(function () {
  var app = document.getElementById('app');
  var toastRegion = document.getElementById('toast-region');
  var currentSell = EcoSell.blank();
  var pending = null;
  var demoListings = [
    { id: 'LIST-DEMO-1', sellerId: 'DEMO-SELLER', sellerIndustry: 'ABC Manufacturing', wasteType: 'Metal Scrap', quantity: 1200, unit: 'kg', price: 95000, location: 'Pune', description: 'High-grade steel scrap suitable for re-melting and industrial reuse.', imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee2279d0d3a8?auto=format&fit=crop&w=900&q=80', availability: 'Available', status: 'LISTED', createdAt: '2026-09-21T00:00:00.000Z' },
    { id: 'LIST-DEMO-2', sellerId: 'DEMO-SELLER-2', sellerIndustry: 'EcoPlast Solutions', wasteType: 'Plastic Waste', quantity: 900, unit: 'kg', price: 62000, location: 'Bengaluru', description: 'Clean HDPE and LDPE polymer waste sorted by grade.', imageUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=900&q=80', availability: 'Available', status: 'LISTED', createdAt: '2026-09-20T00:00:00.000Z' },
    { id: 'LIST-DEMO-3', sellerId: 'DEMO-SELLER', sellerIndustry: 'ABC Manufacturing', wasteType: 'Fly Ash', quantity: 5, unit: 'tonnes', price: 150000, location: 'Nagpur', description: 'Ash by-product with consistent density for construction and filler use.', imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=900&q=80', availability: 'Available', status: 'LISTED', createdAt: '2026-09-18T00:00:00.000Z' }
  ];
  var money = function (value) { return '₹' + Number(value || 0).toLocaleString('en-IN'); };
  var esc = function (value) { return String(value == null ? '' : value).replace(/[&<>'"]/g, function (char) { return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char]; }); };
  var date = function (value) { return value ? new Date(value).toLocaleDateString('en-IN') : '—'; };
  var readForm = function (form) { return Object.fromEntries(new FormData(form).entries()); };

  function seed() {
    if (!localStorage.getItem('ecoexchange_listings')) EcoAuth.write('ecoexchange_listings', demoListings);
    if (!localStorage.getItem('ecoexchange_orders')) EcoAuth.write('ecoexchange_orders', []);
    if (!localStorage.getItem('ecoexchange_logistics')) EcoAuth.write('ecoexchange_logistics', []);
  }
  function route() { return (location.hash || '#home').slice(1); }
  function go(target) { location.hash = target; }
  function notify(message, type) { var node = document.createElement('div'); node.className = 'toast ' + (type || ''); node.textContent = message; toastRegion.appendChild(node); setTimeout(function () { node.remove(); }, 3300); }
  function user() { return EcoAuth.session(); }
  function requireUser() { if (!user()) { notify('Please log in to continue.', 'error'); go('login'); return false; } return true; }
  function logout() {
    EcoAuth.clearSession();
    updateNavigation();
    notify('You have been logged out.');
    go('login');
    render();
  }
  function updateNavigation() {
    var current = user();
    var validRole = current && (current.role === 'USER' || current.role === 'ADMIN');
    var normalUser = validRole && current.role === 'USER';
    var adminUser = validRole && current.role === 'ADMIN';
    var profileLink = document.getElementById('profile-nav');
    var adminLink = document.getElementById('admin-nav');
    var logoutButton = document.getElementById('logout-nav');
    var loginLink = document.getElementById('login-nav');
    if (profileLink) profileLink.hidden = !normalUser;
    if (adminLink) adminLink.hidden = !adminUser;
    if (logoutButton) logoutButton.hidden = !validRole;
    if (loginLink) loginLink.hidden = validRole;
  }

  function header() {
    var active = route().split('/')[0];
    return '<header class="site-header"><div class="header-inner"><a class="brand" href="#home"><span class="brand-mark">E</span><span class="brand-copy"><strong>EcoExchange</strong><small>Turning Industrial Waste Into Valuable Resources.</small></span></a><button class="mobile-toggle" data-action="menu" aria-label="Toggle navigation">☰</button><nav class="nav" id="main-nav"><a class="' + (active === 'home' ? 'active' : '') + '" href="#home">Home</a><a class="' + (active === 'sell' ? 'active' : '') + '" href="#sell">Sell</a><a class="' + (active === 'buy' ? 'active' : '') + '" href="#buy">Buy</a><a class="' + (active === 'dashboard' ? 'active' : '') + '" href="#dashboard">Dashboard</a><a class="' + (active === 'about' ? 'active' : '') + '" href="#about">About</a><a id="profile-nav" class="' + (active === 'profile' ? 'active' : '') + '" href="#profile" hidden>Profile</a><a id="admin-nav" class="' + (active === 'admin' ? 'active' : '') + '" href="#admin" hidden>Admin</a><button id="logout-nav" data-action="logout" hidden>Logout</button><a id="login-nav" class="' + (active === 'login' ? 'active' : '') + '" href="#login">Login</a></nav></div></header>';
  }
  function layout(content) { app.innerHTML = header() + '<main>' + content + '</main><footer class="footer">EcoExchange demo platform · Local browser mode · Built for circular industry.</footer>'; updateNavigation(); }
  function home() {
    layout('<section class="hero"><div><p class="eyebrow">Industrial circularity, made practical</p><h1>Turn Industrial Waste Into Valuable Resources</h1><p class="lead">EcoExchange connects industries that generate industrial waste with businesses that can reuse, recycle, or process those materials.</p><div class="actions"><a class="button primary" href="#sell">Sell Waste</a><a class="button secondary" href="#buy">Buy Waste</a><a class="button ghost" href="#dashboard">Dashboard</a></div></div><div class="hero-panel"><span class="panel-label">Recovered materials this month</span><div class="hero-number">4,820 t</div><div class="panel-grid"><div><strong>39%</strong><span>Lower landfill volume</span></div><div><strong>12K</strong><span>Logistics miles saved</span></div></div></div></section><section class="section"><div class="section-heading"><div><p class="eyebrow">How EcoExchange Works</p><h2>Simple chain. Circular impact.</h2></div></div><div class="steps">' + ['List Waste', 'Discover Materials', 'Place Order', 'Logistics Pickup', 'Complete Exchange'].map(function (item, i) { return '<div class="step"><b>' + (i + 1) + '</b><strong>' + item + '</strong></div>'; }).join('') + '</div></section><section class="section"><div class="section-heading"><div><p class="eyebrow">Marketplace pulse</p><h2>Measurable impact for industry</h2></div></div><div class="stat-grid"><div class="stat"><small>Industries Connected</small><strong>320+</strong></div><div class="stat"><small>Waste Listed</small><strong>48.6K kg</strong></div><div class="stat"><small>Orders Completed</small><strong>1,430</strong></div><div class="stat"><small>Waste Exchanged</small><strong>92%</strong></div></div></section><section class="section"><div class="benefit-grid"><div class="benefit"><strong>Verified connections</strong><p>Find credible industry partners with clear material details and locations.</p></div><div class="benefit"><strong>Transparent pricing</strong><p>See commissions, transport charges, and the final amount before ordering.</p></div><div class="benefit"><strong>Coordinated logistics</strong><p>Keep every exchange moving from listing to pickup and delivery.</p></div></div></section>');
  }
  function about() { layout('<section class="page-head"><div><p class="eyebrow">About EcoExchange</p><h1>Industrial by-products deserve a second market.</h1><p>EcoExchange gives manufacturers, recyclers, and processors one shared place to discover materials, negotiate value, and coordinate the physical exchange.</p></div></section><section class="benefit-grid"><div class="benefit"><strong>Reuse first</strong><p>Make useful materials visible before they become disposal costs.</p></div><div class="benefit"><strong>Evidence over guesswork</strong><p>Every listing carries quantity, unit, price, location, and description.</p></div><div class="benefit"><strong>One connected workflow</strong><p>Seller, buyer, administrator, and logistics partner can follow the same order.</p></div></section>'); }

  function authPage(mode) {
    var register = mode === 'register';
    layout('<div class="auth-wrap"><section class="auth-card"><p class="eyebrow">' + (register ? 'Join EcoExchange' : 'Welcome back') + '</p><h2>' + (register ? 'Create your industry account' : 'Login to EcoExchange') + '</h2>' + (register ? '<form id="register-form" class="form-grid"><label>Industry Name<input name="industryName" required></label><label>Owner Name<input name="ownerName" required></label><label>Email<input name="email" type="email" required></label><label>Location<input name="location" required></label><label>Contact Number<input name="contactNumber" required></label><label>Create Password<input name="password" type="password" minlength="8" required></label><label>Confirm Password<input name="confirmPassword" type="password" minlength="8" required></label><div class="full button-row"><button class="button primary">Register</button><a class="button ghost" href="#login">Already have an account?</a></div></form>' : '<form id="login-form" novalidate><div class="form-grid"><label>Email<input name="email" type="email" placeholder="Enter your email" required></label><label>Password<input name="password" type="password" placeholder="Enter your password" required></label></div><div class="button-row"><button class="button primary">Login</button><a class="button ghost" href="#register">Create Account</a></div></form>') + '</section></div>');
  }

  function dashboard() {
    if (!requireUser()) return;
    var current = user(), stats = EcoDashboard.stats(current), orders = EcoDashboard.ordersFor(current), listings = EcoDashboard.listingsFor(current);
    var profile = '<div class="profile-grid"><div class="profile-item"><small>Industry Name</small><strong>' + esc(current.industryName) + '</strong></div><div class="profile-item"><small>Owner Name</small><strong>' + esc(current.ownerName) + '</strong></div><div class="profile-item"><small>Email</small><strong>' + esc(current.email) + '</strong></div><div class="profile-item"><small>Contact Number</small><strong>' + esc(current.contactNumber) + '</strong></div><div class="profile-item"><small>Location</small><strong>' + esc(current.location) + '</strong></div><div class="profile-item"><small>Account</small><strong>' + (current.role === 'ADMIN' ? 'Administrator' : 'Industry') + '</strong></div></div>';
    var statHtml = [['Total Sales', money(stats.sales)], ['Total Purchases', money(stats.purchases)], ['Active Orders', stats.active], ['Completed Orders', stats.completed], ['Total Waste Listed', stats.listed], ['Total Waste Purchased', stats.purchased]].map(function (item) { return '<div class="mini-stat"><strong>' + item[1] + '</strong><span>' + item[0] + '</span></div>'; }).join('');
    var orderRows = orders.length ? orders.slice(0, 8).map(function (o) { return '<tr><td><strong>' + esc(o.orderCode) + '</strong></td><td>' + esc(o.wasteType) + '</td><td>' + (o.buyerId === current.id ? 'Purchase' : 'Sale') + '</td><td>' + money(o.finalAmount) + '</td><td>' + EcoOrders.badge(o.status) + '</td><td>' + date(o.createdAt) + '</td></tr>'; }).join('') : '<tr><td colspan="6">No orders yet. Place an order from the Buy page to see it here.</td></tr>';
    var listingRows = listings.length ? listings.map(function (l) { return '<tr><td>' + esc(l.wasteType) + '</td><td>' + l.quantity + ' ' + esc(l.unit) + '</td><td>' + money(l.price) + '</td><td>' + esc(l.location) + '</td><td>' + EcoOrders.badge(l.status) + '</td></tr>'; }).join('') : '<tr><td colspan="5">No listings yet. Create your first listing from Sell.</td></tr>';
    layout('<div class="page-head"><div><p class="eyebrow">Industry dashboard</p><h1>Good to see you, ' + esc(current.ownerName) + '.</h1><p>Track your material exchange activity in one place.</p></div><a class="button primary" href="#sell">+ List Waste</a></div><div class="dashboard-layout"><aside class="side-card"><h3>Workspace</h3><ul class="side-list"><li><button class="active">Overview</button></li><li><button data-route="sell">Sell Waste</button></li><li><button data-route="buy">Buy Materials</button></li><li><button data-action="logout">Logout</button></li></ul></aside><div class="content-stack"><section class="card"><h3>Industry profile</h3>' + profile + '</section><section class="card"><h3>Overview</h3><div class="mini-stat-grid">' + statHtml + '</div></section><section class="table-card"><h3>Recent Orders</h3><div class="table-scroll"><table><thead><tr><th>Order ID</th><th>Waste Type</th><th>Type</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody>' + orderRows + '</tbody></table></div></section><section class="table-card"><h3>Recent Sales / Listings</h3><div class="table-scroll"><table><thead><tr><th>Waste Type</th><th>Quantity</th><th>Price</th><th>Location</th><th>Status</th></tr></thead><tbody>' + listingRows + '</tbody></table></div></section></div></div>');
  }

  function profile() {
    var current = user();
    if (!current || current.role !== 'USER') {
      notify('Please login to view your profile.', 'error');
      go('login');
      return;
    }
    layout('<div class="page-head"><div><p class="eyebrow">Your account</p><h1>Profile</h1><p>Review your industry account details.</p></div></div><section class="auth-card"><div class="profile-grid"><div class="profile-item"><small>Industry Name</small><strong>' + esc(current.industryName) + '</strong></div><div class="profile-item"><small>Owner Name</small><strong>' + esc(current.ownerName) + '</strong></div><div class="profile-item"><small>Email</small><strong>' + esc(current.email) + '</strong></div><div class="profile-item"><small>Contact Number</small><strong>' + esc(current.contactNumber) + '</strong></div><div class="profile-item"><small>Location</small><strong>' + esc(current.location) + '</strong></div></div></section>');
  }

  function sell() {
    if (!requireUser()) return;
    var data = currentSell, commission = Number(data.price || 0) * .02, net = Number(data.price || 0) - commission;
    layout('<div class="page-head"><div><p class="eyebrow">Seller workspace</p><h1>List a material for exchange.</h1><p>Give buyers enough detail to make a confident reuse decision.</p></div></div><section class="auth-card"><form id="sell-form" class="form-grid"><label>Waste Type<select name="wasteType">' + EcoSell.types.map(function (type) { return '<option ' + (data.wasteType === type ? 'selected' : '') + '>' + type + '</option>'; }).join('') + '</select></label><label>Waste Photo<input name="photo" type="file" accept="image/*"><img id="image-preview" class="image-preview ' + (data.imageUrl ? 'visible' : '') + '" src="' + esc(data.imageUrl) + '" alt="Waste preview"></label><label>Quantity<input name="quantity" type="number" min="1" value="' + esc(data.quantity) + '" required></label><label>Unit<select name="unit"><option>kg</option><option>tonnes</option><option>litres</option><option>units</option></select></label><label>Price<input name="price" id="sell-price" type="number" min="1" value="' + esc(data.price) + '" required></label><label>Location<input name="location" value="' + esc(data.location) + '" required></label><label class="full">Description<textarea name="description" rows="4" required>' + esc(data.description) + '</textarea></label><div class="summary-box full"><div class="summary-row"><span>Listed Price</span><strong id="sell-base">' + money(data.price) + '</strong></div><div class="summary-row"><span>Seller Commission (2%)</span><strong id="seller-fee">' + money(commission) + '</strong></div><div class="summary-row total"><span>Net Amount</span><strong id="seller-net">' + money(net) + '</strong></div></div><div class="full button-row"><button class="button primary">Place Order / Listing</button><a class="button ghost" href="#dashboard">Cancel</a></div></form></section>');
  }

  function buy(filters) {
    filters = filters || { search: '', type: 'All', location: 'All', sort: 'newest' };
    var all = EcoBuy.listings().filter(function (item) { var q = filters.search.toLowerCase(); return (!q || (item.wasteType + ' ' + item.location + ' ' + item.sellerIndustry).toLowerCase().includes(q)) && (filters.type === 'All' || item.wasteType === filters.type) && (filters.location === 'All' || item.location === filters.location) && (!filters.minPrice || item.price >= Number(filters.minPrice)) && (!filters.minQuantity || item.quantity >= Number(filters.minQuantity)); });
    all.sort(function (a, b) { return filters.sort === 'low' ? a.price - b.price : filters.sort === 'high' ? b.price - a.price : new Date(b.createdAt) - new Date(a.createdAt); });
    var types = [...new Set(EcoBuy.listings().map(function (i) { return i.wasteType; }))], locations = [...new Set(EcoBuy.listings().map(function (i) { return i.location; }))];
    var cards = all.length ? all.map(function (item) { return '<article class="listing"><img src="' + esc(EcoBuy.image(item)) + '" alt="' + esc(item.wasteType) + '"><div class="listing-body"><div class="listing-top"><span class="badge">' + esc(item.wasteType) + '</span><strong>' + money(item.price) + '</strong></div><h3>' + esc(item.sellerIndustry) + '</h3><p>' + esc(item.description) + '</p><div class="listing-meta"><span>' + item.quantity + ' ' + esc(item.unit) + '</span><span>' + esc(item.location) + '</span></div><div class="button-row"><a class="button secondary small" href="#buy/' + item.id + '">View Details</a><a class="button primary small" href="#buy/' + item.id + '">Place Order</a></div></div></article>'; }).join('') : '<div class="empty"><h3>No matching listings</h3><p>Try a different search or list a new material.</p></div>';
    layout('<div class="page-head"><div><p class="eyebrow">Buyer marketplace</p><h1>Find materials ready for reuse.</h1><p>Compare industrial by-products by material, location, quantity, and price.</p></div><a class="button primary" href="#sell">+ Sell Waste</a></div><form id="filters-form" class="filters"><input name="search" value="' + esc(filters.search) + '" placeholder="Search material, location, industry"><select name="type"><option>All</option>' + types.map(function (x) { return '<option ' + (filters.type === x ? 'selected' : '') + '>' + esc(x) + '</option>'; }).join('') + '</select><select name="location"><option>All</option>' + locations.map(function (x) { return '<option ' + (filters.location === x ? 'selected' : '') + '>' + esc(x) + '</option>'; }).join('') + '</select><input name="minPrice" type="number" min="0" value="' + esc(filters.minPrice || '') + '" placeholder="Min price"><input name="minQuantity" type="number" min="0" value="' + esc(filters.minQuantity || '') + '" placeholder="Min quantity"><select name="sort"><option value="newest" ' + (filters.sort === 'newest' ? 'selected' : '') + '>Newest</option><option value="low" ' + (filters.sort === 'low' ? 'selected' : '') + '>Price: Low to High</option><option value="high" ' + (filters.sort === 'high' ? 'selected' : '') + '>Price: High to Low</option></select><button class="button primary">Filter</button></form><div class="listing-grid">' + cards + '</div>');
  }

  function buyDetail(id) {
    var listing = EcoBuy.find(id);
    if (!listing) { buy(); return; }
    var totals = EcoBuy.totals(listing);
    layout('<div class="page-head"><div><p class="eyebrow">Material details</p><h1>' + esc(listing.wasteType) + '</h1><p>Review the complete order economics before confirming.</p></div><a class="button ghost" href="#buy">← Back to marketplace</a></div><section class="detail-card"><img src="' + esc(EcoBuy.image(listing)) + '" alt="' + esc(listing.wasteType) + '"><div class="detail-copy"><span class="badge">Available</span><h2>' + esc(listing.sellerIndustry) + '</h2><div class="detail-meta"><span>' + listing.quantity + ' ' + esc(listing.unit) + '</span><span>' + esc(listing.location) + '</span><span>Listed ' + date(listing.createdAt) + '</span></div><p class="muted" style="margin-top:18px">' + esc(listing.description) + '</p><div class="summary-box"><div class="summary-row"><span>Base Price</span><strong>' + money(totals.base) + '</strong></div><div class="summary-row"><span>Buyer Commission (5%)</span><strong>' + money(totals.commission) + '</strong></div><div class="summary-row"><span>Transport Charge</span><strong>' + money(totals.transport) + '</strong></div><div class="summary-row total"><span>Final Price</span><strong>' + money(totals.final) + '</strong></div></div><button class="button primary" data-action="buy-confirm" data-id="' + listing.id + '">Place Order</button></div></section>');
  }

  function orderModal(listing) { var totals = EcoBuy.totals(listing); pending = { kind: 'order', listing: listing }; document.body.insertAdjacentHTML('beforeend', '<div class="confirm-modal" id="modal"><section class="modal-card"><div class="modal-head"><div><p class="eyebrow">Final review</p><h2>Confirm your order</h2></div><button class="close" data-action="close-modal">×</button></div><p class="muted">You are ordering ' + esc(listing.quantity + ' ' + listing.unit + ' of ' + listing.wasteType) + ' from ' + esc(listing.sellerIndustry) + '.</p><div class="summary-box"><div class="summary-row"><span>Base Price</span><strong>' + money(totals.base) + '</strong></div><div class="summary-row"><span>5% Buyer Commission</span><strong>' + money(totals.commission) + '</strong></div><div class="summary-row"><span>Transport Charges</span><strong>' + money(totals.transport) + '</strong></div><div class="summary-row total"><span>Final Price</span><strong>' + money(totals.final) + '</strong></div></div><div class="button-row"><button class="button primary" data-action="confirm-order">Confirm & Place Order</button><button class="button ghost" data-action="close-modal">Back</button></div></section></div>'); }
  function orderDetail(order) { var steps = EcoOrders.timeline(order.status); return '<div class="confirm-modal" id="modal"><section class="modal-card"><div class="modal-head"><div><p class="eyebrow">Order tracking</p><h2>' + esc(order.orderCode) + '</h2></div><button class="close" data-action="close-modal">×</button></div><p><strong>' + esc(order.wasteType) + '</strong> · ' + money(order.finalAmount) + ' · ' + EcoOrders.badge(order.status) + '</p><div class="timeline">' + steps.map(function (step, i) { return '<div class="timeline-step ' + (step.done ? 'done' : '') + '"><span class="timeline-dot">' + (step.done ? '✓' : '·') + '</span><strong>' + step.label + '</strong></div>'; }).join('') + '</div></section></div>'; }

  function admin() {
    if (!requireUser()) return;
    if (user().role !== 'ADMIN') { notify('You do not have permission to view this page.', 'error'); go('home'); return; }
    var section = route().split('/')[1] || 'overview';
    var overview = EcoAdmin.overview(), orders = EcoOrders.all(), listings = EcoBuy.listings(), requests = EcoAdmin.requests(), users = EcoAuth.users();
    var sellers = [...new Map(listings.map(function (item) { return [item.sellerIndustry, { industryName: item.sellerIndustry, ownerName: 'Marketplace seller', email: 'Listing contact', contactNumber: '—', location: item.location, createdAt: item.createdAt }]; })).values()];
    users.filter(function (item) { return item.role !== 'ADMIN'; }).forEach(function (item) { if (!sellers.some(function (seller) { return seller.industryName === item.industryName; })) sellers.push(item); });
    var buyers = [...new Map(orders.map(function (item) { return [item.buyerIndustry, { industryName: item.buyerIndustry, ownerName: 'Order buyer', email: 'Order contact', contactNumber: '—', location: item.location, createdAt: item.createdAt }]; })).values()];
    var navItems = [['overview', 'Overview'], ['orders', 'Orders'], ['sellers', 'Sellers'], ['buyers', 'Buyers'], ['listings', 'Waste Listings'], ['logistics', 'Logistics'], ['transactions', 'Transactions']];
    var nav = navItems.map(function (item) { return '<li><a class="' + (section === item[0] ? 'active' : '') + '" href="#admin/' + item[0] + '">' + item[1] + '</a></li>'; }).join('');
    var rows = orders.length ? orders.map(function (o) { return '<tr><td><button class="button ghost small" data-action="order-detail" data-id="' + o.id + '">' + esc(o.orderCode) + '</button></td><td>' + esc(o.sellerIndustry) + '</td><td>' + esc(o.buyerIndustry) + '</td><td>' + esc(o.wasteType) + '</td><td>' + o.quantity + '</td><td>' + money(o.basePrice) + '</td><td>' + money(o.buyerCommission) + '</td><td>' + money(o.transportCharge) + '</td><td>' + money(o.finalAmount) + '</td><td>' + EcoOrders.badge(o.status) + '</td><td>' + date(o.createdAt) + '</td><td>' + (o.status === 'ORDER_PLACED' || o.status === 'ADMIN_REVIEW' ? '<button class="button primary small" data-action="forward" data-id="' + o.id + '">Forward to Logistics</button>' : '<select data-action="status" data-id="' + o.id + '">' + EcoOrders.statuses.map(function (s) { return '<option ' + (s === o.status ? 'selected' : '') + '>' + s + '</option>'; }).join('') + '</select>') + '</td></tr>'; }).join('') : '<tr><td colspan="12">No orders yet. Buyer orders will appear here.</td></tr>';
    var logisticsRows = requests.length ? requests.map(function (r) { var requestOrder = orders.find(function (o) { return o.id === r.orderId; }); return '<tr><td>' + r.id + '</td><td>' + (requestOrder ? esc(requestOrder.orderCode) : esc(r.orderId)) + '</td><td>' + esc(r.companyName) + '</td><td>' + EcoOrders.badge(r.status) + '</td><td><select data-action="logistics-status" data-id="' + r.id + '">' + ['ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'DELIVERED', 'COMPLETED'].map(function (status) { return '<option ' + (status === r.status ? 'selected' : '') + '>' + status + '</option>'; }).join('') + '</select></td></tr>'; }).join('') : '<tr><td colspan="5">No logistics requests yet. Forward an order to create one.</td></tr>';
    var listingRows = listings.map(function (listing) { return '<tr><td>' + esc(listing.id) + '</td><td>' + esc(listing.sellerIndustry) + '</td><td>' + esc(listing.wasteType) + '</td><td>' + listing.quantity + ' ' + esc(listing.unit) + '</td><td>' + money(listing.price) + '</td><td>' + esc(listing.location) + '</td><td>' + EcoOrders.badge(listing.status) + '</td></tr>'; }).join('') || '<tr><td colspan="7">No waste listings yet.</td></tr>';
    var peopleRows = function (items) { return items.map(function (item) { return '<tr><td>' + esc(item.industryName) + '</td><td>' + esc(item.ownerName) + '</td><td>' + esc(item.email) + '</td><td>' + esc(item.contactNumber) + '</td><td>' + esc(item.location) + '</td><td>' + date(item.createdAt) + '</td></tr>'; }).join('') || '<tr><td colspan="6">No registered industries yet.</td></tr>'; };
    var transactionRows = orders.map(function (o) { return '<tr><td>' + esc(o.orderCode) + '</td><td>BUY</td><td>' + money(o.finalAmount) + '</td><td>' + EcoOrders.badge(o.status) + '</td><td>' + date(o.createdAt) + '</td></tr>'; }).join('') || '<tr><td colspan="5">No transactions yet.</td></tr>';
    var stats = '<div class="stat-grid"><div class="stat"><small>Total Orders</small><strong>' + overview.totalOrders + '</strong></div><div class="stat"><small>Pending Orders</small><strong>' + overview.pending + '</strong></div><div class="stat"><small>Forwarded Orders</small><strong>' + overview.forwarded + '</strong></div><div class="stat"><small>Completed Orders</small><strong>' + overview.completed + '</strong></div><div class="stat"><small>Total Waste</small><strong>' + overview.waste + '</strong></div><div class="stat"><small>Total Industries</small><strong>' + overview.industries + '</strong></div></div>';
    var content = stats;
    if (section === 'orders' || section === 'overview') content += '<section class="table-card"><h3>' + (section === 'overview' ? 'Recent Orders' : 'All Orders') + '</h3><div class="table-scroll"><table><thead><tr><th>Order ID</th><th>Seller</th><th>Buyer</th><th>Waste Type</th><th>Qty</th><th>Base Price</th><th>Commission</th><th>Transport</th><th>Final</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody>' + rows + '</tbody></table></div></section>';
    if (section === 'sellers') content += '<section class="table-card"><h3>Sellers</h3><div class="table-scroll"><table><thead><tr><th>Industry</th><th>Owner</th><th>Email</th><th>Contact</th><th>Location</th><th>Joined</th></tr></thead><tbody>' + peopleRows(sellers) + '</tbody></table></div></section>';
    if (section === 'buyers') content += '<section class="table-card"><h3>Buyers</h3><div class="table-scroll"><table><thead><tr><th>Industry</th><th>Owner</th><th>Email</th><th>Contact</th><th>Location</th><th>Joined</th></tr></thead><tbody>' + peopleRows(buyers) + '</tbody></table></div></section>';
    if (section === 'listings') content += '<section class="table-card"><h3>Waste Listings</h3><div class="table-scroll"><table><thead><tr><th>Listing ID</th><th>Seller</th><th>Waste Type</th><th>Quantity</th><th>Price</th><th>Location</th><th>Status</th></tr></thead><tbody>' + listingRows + '</tbody></table></div></section>';
    if (section === 'logistics') content += '<section class="table-card"><h3>Logistics Requests</h3><div class="table-scroll"><table><thead><tr><th>Request</th><th>Order</th><th>Company</th><th>Status</th><th>Update Status</th></tr></thead><tbody>' + logisticsRows + '</tbody></table></div></section><section class="card"><h3>Available logistics companies</h3><div class="benefit-grid">' + EcoAdmin.companies.map(function (c) { return '<div class="benefit"><strong>' + c.name + '</strong><p>' + c.area + '</p></div>'; }).join('') + '</div></section>';
    if (section === 'transactions') content += '<section class="table-card"><h3>Transactions</h3><div class="table-scroll"><table><thead><tr><th>Order</th><th>Type</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody>' + transactionRows + '</tbody></table></div></section>';
    layout('<div class="page-head"><div><p class="eyebrow">Administration</p><h1>Control the exchange network.</h1><p>Review shared marketplace data, assign logistics, and move materials through the chain.</p></div></div><div class="admin-layout"><aside class="side-card"><h3>Admin workspace</h3><ul class="side-list">' + nav + '</ul></aside><div class="content-stack">' + content + '</div></div>');
  }

  function render() { var current = route(); if (current.indexOf('buy/') === 0) return buyDetail(current.split('/')[1]); if (current === 'home') return home(); if (current === 'about') return about(); if (current === 'register') return authPage('register'); if (current === 'login') return authPage('login'); if (current === 'profile') return profile(); if (current === 'dashboard') return dashboard(); if (current === 'sell') return sell(); if (current === 'buy') return buy(); if (current === 'admin' || current.indexOf('admin/') === 0) return admin(); return home(); }

  document.addEventListener('click', function (event) {
    var target = event.target.closest('[data-action], [data-route]'); if (!target) return;
    var action = target.dataset.action;
    if (target.dataset.route) { event.preventDefault(); go(target.dataset.route); return; }
    if (action === 'menu') document.getElementById('main-nav').classList.toggle('open');
    if (action === 'logout') { event.preventDefault(); event.stopPropagation(); logout(); return; }
    if (action === 'close-modal') { var modal = document.getElementById('modal'); if (modal) modal.remove(); pending = null; }
    if (action === 'buy-confirm') { if (requireUser()) orderModal(EcoBuy.find(target.dataset.id)); }
    if (action === 'confirm-order') { var current = user(), listing = pending.listing, totals = EcoBuy.totals(listing); var order = { id: 'ORD-' + Date.now(), orderCode: 'ECO-BUY-' + String(EcoOrders.all().length + 1).padStart(5, '0'), sellerId: listing.sellerId, sellerIndustry: listing.sellerIndustry, buyerId: current.id, buyerIndustry: current.industryName, wasteType: listing.wasteType, quantity: listing.quantity, location: listing.location, basePrice: totals.base, buyerCommission: totals.commission, sellerCommission: totals.base * .02, transportCharge: totals.transport, finalAmount: totals.final, status: 'ORDER_PLACED', createdAt: new Date().toISOString() }; EcoOrders.save(order); document.getElementById('modal').remove(); pending = null; notify('Order placed successfully.'); go('dashboard'); }
    if (action === 'order-detail') { var found = EcoOrders.all().find(function (o) { return o.id === target.dataset.id; }); document.body.insertAdjacentHTML('beforeend', orderDetail(found)); }
    if (action === 'forward') { var order = EcoOrders.all().find(function (o) { return o.id === target.dataset.id; }); pending = { kind: 'forward', order: order }; document.body.insertAdjacentHTML('beforeend', '<div class="confirm-modal" id="modal"><section class="modal-card"><div class="modal-head"><div><p class="eyebrow">Logistics handoff</p><h2>Assign logistics company</h2></div><button class="close" data-action="close-modal">×</button></div><p class="muted">Choose a partner for ' + esc(order.orderCode) + '.</p><select id="logistics-company">' + EcoAdmin.companies.map(function (c) { return '<option value="' + c.id + '">' + c.name + ' · ' + c.area + '</option>'; }).join('') + '</select><div class="button-row" style="margin-top:18px"><button class="button primary" data-action="assign">Assign Logistics</button><button class="button ghost" data-action="close-modal">Cancel</button></div></section></div>'); }
    if (action === 'assign') { var companyId = document.getElementById('logistics-company').value; EcoAdmin.forward(pending.order, companyId); document.getElementById('modal').remove(); pending = null; notify('Order forwarded and logistics assigned.'); render(); }
  });
  document.addEventListener('submit', function (event) {
    var form = event.target; if (!form.id) return; event.preventDefault(); var data = readForm(form);
    if (form.id === 'register-form') { if (data.password !== data.confirmPassword) return notify('Passwords do not match.', 'error'); try { EcoAuth.register(data); notify('Registration successful.'); go('dashboard'); } catch (error) { notify(error.message, 'error'); } }
    if (form.id === 'login-form') { try { var logged = EcoAuth.login(data.email, data.password); notify('Login successful.'); go(logged.role === 'ADMIN' ? 'admin' : 'dashboard'); } catch (error) { notify('Invalid email or password.', 'error'); } }
    if (form.id === 'sell-form') { if (!requireUser()) return; if (!data.description.trim()) return notify('Description is required.', 'error'); data.imageUrl = currentSell.imageUrl || ''; delete data.photo; EcoSell.save(data, user()); currentSell = EcoSell.blank(); notify('Waste listing created successfully.'); go('dashboard'); }
    if (form.id === 'filters-form') { buy(data); }
  });
  document.addEventListener('input', function (event) { if (event.target.id === 'sell-price') { var value = Number(event.target.value || 0), fee = value * .02; document.getElementById('sell-base').textContent = money(value); document.getElementById('seller-fee').textContent = money(fee); document.getElementById('seller-net').textContent = money(value - fee); } });
  document.addEventListener('change', function (event) { if (event.target.name === 'photo' && event.target.files[0]) { var reader = new FileReader(); reader.onload = function (e) { currentSell.imageUrl = e.target.result; var preview = document.getElementById('image-preview'); preview.src = e.target.result; preview.classList.add('visible'); }; reader.readAsDataURL(event.target.files[0]); } if (event.target.dataset.action === 'status') { EcoOrders.update(event.target.dataset.id, { status: event.target.value }); notify('Order status updated.'); render(); } if (event.target.dataset.action === 'logistics-status') { EcoAdmin.updateRequest(event.target.dataset.id, event.target.value); notify('Logistics and order status updated.'); render(); } });
  window.addEventListener('hashchange', render);
  window.addEventListener('storage', function (event) { if (event.key === 'currentUser' || event.key === 'ecoexchange_session') { updateNavigation(); render(); } });
  seed(); render();
}());
